name: Build Alpha Release

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log Level"
        default: "debug"
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Git
      run: |
        git config --global user.name 'Deploy Bot'
        git config --global user.email '60839662+acbgbca@users.noreply.github.com'
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Release Prepare
      run: mvn -B release:prepare
    - name: Release Perform
      run: mvn -B release:perform -Darguments="-Dmaven.deploy.skip=true"
   
