name: Verify Pull Requests

on:
  workflow_dispatch:
    inputs:
      log_level:
        description: "Log Level"
        default: "debug"
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Run test suite
      run: mvn -B clean verify --file pom.xml
