name: Build Playwright Proxy

on:
  release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/acbgbca/playwright-proxy:${GITHUB_REF_NAME}
          ghcr.io/acbgbca/playwright-proxy:latest
    - name: Increment version
      run: mvn versions:set -DnewVersion=$(echo ${GITHUB_REF_NAME} | awk -F. -v OFS=. '{$NF += 1 ; print}')
    - name: Commit updated file
      run: git add pom.xml && git commit -m 'chore increment version for next release'
